### ISSUE TITLE
Vapor Progress Tracker

### ISSUE THREAD

**Issue by kumavis** [ethereum/vapor#11]
#### primary
- [x] identity management - storage + retrieval ( 3 hrs )
- [x] generate an identity ( 1 hrs )
- [ ] import identity ( 3 hrs )
- [ ] primary identity selection ( 5 hrs )
- [ ] user transaction confirmation ( 5 hrs )
- [ ] multi-client rpc server ( 5 hrs )
- [x] multi-client rpc on heroku/etc ( 3 hrs )
- [x] host vapor webapp on gh-pages ( 2 hrs )
- [ ] hyperboot container ( 5 hrs )
- [ ] hyperboot ui/settings ( 8 hrs )
- [ ] dapp loading (e.g. external resources) ( 1 week )
- [ ] dapp requesting (registry, urlhint) [wiki](https://github.com/ethereum/wiki/wiki/URL-Hint-Protocol) ( ? )

#### visual polish
- [ ] login flow
- [ ] importing + exporting identities
- [ ] primary identity selection
- [ ] dapp browsing
- [ ] first visit flow / tutorial
- [ ] upgrade process

#### Extras
- [ ] remove nw.js from builds
- [ ] clear state debug button
- [ ] gulp - use plumber to fix break on error
- [ ] tests mothafucka
- [ ] app usage timeout (lockout user)
- [ ] export identity

**Comment by fractastical** [comment]
did that submit a pull request?

**Comment by kumavis** [comment]
priorities
1) secure identity management
2) dapp loading
3) multi-rpc server
4) UX
5) hyperboot

**Comment by kumavis** [comment]
lots of stuff on hackframe to fix, need it to expose web3 -- and need to re-up the multi-rpc-client to take commands for embedding contracts

kumavis [11:00 PM]
move dapp processing to rpc or other service

**Comment by kumavis** [comment]
continued here https://github.com/ethereum/vapor/issues/13
